name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NX_NON_NATIVE_HASHER: true

jobs:
  audit:
    runs-on: ubuntu-latest
    name: Audit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Audit production dependencies
        run: npm audit --omit=dev --omit=optional

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # @TODO add windows-latest after we have the os agnostic macher
    name: Unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Set base and head for Nx affected commands
        uses: nrwl/nx-set-shas@v4
      - name: Install dependencies
        run: npm ci
      - name: Unit test affected projects
        run: npx nx affected -t unit-test --parallel=3 --verbose --coverage.enabled

  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # @TODO add windows-latest after we know why it is running forever
    name: E2E tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Set base and head for Nx affected commands
        uses: nrwl/nx-set-shas@v4
      - name: Install dependencies
        run: npm i
      - name: E2E test affected projects
        run: npx nx affected -t e2e --exclude="tag:type:example"
